AWSTemplateFormatVersion: "2010-09-09"

Description: ECS stack for microservices project - Cluster, ECS task definition and service

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - staging
      - dev
      - prod
    Description: Environment name used to tag and name all resources

  ClusterName:
    Type: String
    Default: microservices-cluster
    Description: Name of the ECS cluster

  Region:
    Type: String
    Default: eu-central-1
    Description: AWS region for the resource
  


Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  UserEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Environment}-user-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: "${Environment}-ecs-task-execution-role"
      TaskRoleArn: !ImportValue
        Fn::Sub: "${Environment}-user-task-role"
      ContainerDefinitions:
        - Name: user-service-container
          Image: !ImportValue
            Fn::Sub: "${Environment}-user-repo-uri"
          Essential: true
          PortMappings:
            - ContainerPort: 3001
              HostPort: 3001
              Protocol: tcp
          Environment:
            - Name: AWS_REGION
              Value: !Ref Region

            - Name: DB_USER
              Value: dbadmin

            - Name: DB_NAME
              Value: userdb

            - Name: DB_PORT
              Value: 5432

            - Name: DB_HOST
              Value: 
                Fn::ImportValue: userdb-endpoint
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: !Sub
                - "${SecretArn}:password::"
                - SecretArn: !ImportValue
                    Fn::Sub: "${Environment}-userdb-master-secret-arn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: "${Environment}-user-service-log-group-name"
              awslogs-region: !Ref Region
              awslogs-stream-prefix: user


  UserEcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: !Sub "${Environment}-user-service"
      TaskDefinition: !Ref UserEcsTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-1-id"
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-2-id"
          SecurityGroups:
            - !ImportValue
              Fn::Sub: "${Environment}-user-sg-id"    
      LoadBalancers:
        - TargetGroupArn: !ImportValue
            Fn::Sub: "${Environment}-UserServiceTargetGroupARN"
          ContainerName: user-service-container
          ContainerPort: 3001


  
  ProductEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Environment}-product-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: "${Environment}-ecs-task-execution-role"
      TaskRoleArn: !ImportValue
        Fn::Sub: "${Environment}-product-task-role"
      ContainerDefinitions:
        - Name: product-service-container
          Image: !ImportValue
            Fn::Sub: "${Environment}-product-repo-uri"
          Essential: true
          PortMappings:
            - ContainerPort: 3002
              HostPort: 3002
              Protocol: tcp
          Environment:
            - Name: DB_USER
              Value: dbadmin

            - NAME: DB_NAME
              Value: productdb

            - Name: DB_PORT
              Value: 5432

            - Name: DB_HOST
              Value:
                Fn::ImportValue: productdb-endpoint    

            - Name: Region
              Value: !Ref Region
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: !Sub
                - "${SecretArn}:password::"
                - SecretArn: !ImportValue
                    Fn::Sub: "${Environment}-productdb-master-secret-arn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: "${Environment}-product-service-log-group-name"
              awslogs-region: !Ref Region
              awslogs-stream-prefix: product

  ProductEcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: !Sub "${Environment}-product-service"
      TaskDefinition: !Ref ProductEcsTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-1-id"
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-2-id"
          SecurityGroups:
            - !ImportValue
              Fn::Sub: "${Environment}-product-sg-id"    
      LoadBalancers:
        - TargetGroupArn: !ImportValue
            Fn::Sub: "${Environment}-ProductServiceTargetGroupARN"
          ContainerName: product-service-container
          ContainerPort: 3002


  OrderEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Environment}-order-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: "${Environment}-ecs-task-execution-role"
      TaskRoleArn: !ImportValue
        Fn::Sub: "${Environment}-order-task-role"
      ContainerDefinitions:
        - Name: order-service-container
          Image: !ImportValue
            Fn::Sub: "${Environment}-order-repo-uri"
          Essential: true
          PortMappings:
            - ContainerPort: 3003
              HostPort: 3003
              Protocol: tcp
          Environment:
            - Name: AWS_REGION
              Value: !Ref Region

            - Name: DB_USER
              Value: dbadmin

            - Name: DB_NAME
              Value: orderdb

            - Name: DB_PORT
              Value: 5432

            - Name: DB_HOST
              Value: 
                Fn::ImportValue: orderdb-endpoint
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: !Sub
                - "${SecretArn}:password::"
                - SecretArn: !ImportValue
                    Fn::Sub: "${Environment}-orderdb-master-secret-arn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: "${Environment}-order-service-log-group-name"
              awslogs-region: !Ref Region
              awslogs-stream-prefix: order

  OrderEcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster  
      ServiceName: !Sub "${Environment}-order-service"
      TaskDefinition: !Ref OrderEcsTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-1-id"
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-2-id"
          SecurityGroups:
            - !ImportValue
              Fn::Sub: "${Environment}-order-sg-id"    
      LoadBalancers:
        - TargetGroupArn: !ImportValue
            Fn::Sub: "${Environment}-OrderServiceTargetGroupARN"
          ContainerName: order-service-container
          ContainerPort: 3003



  NotificationEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Environment}-notification-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: "${Environment}-ecs-task-execution-role"
      TaskRoleArn: !ImportValue
        Fn::Sub: "${Environment}-notification-task-role"
      ContainerDefinitions:
        - Name: notification-service-container
          Image: !ImportValue
            Fn::Sub: "${Environment}-notification-repo-uri"
          Essential: true
          PortMappings:
            - ContainerPort: 3004
              HostPort: 3004
              Protocol: tcp
          Environment:
            - Name: SQS_QUEUE_URL
              Value: !ImportValue
                Fn::Sub: "${Environment}-SQSQueueURL"
            
            - Name: Region
              Value: !Ref Region
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: "${Environment}-notification-service-log-group-name"
              awslogs-region: !Ref Region
              awslogs-stream-prefix: notification

  NotificationEcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster 
      TaskDefinition: !Ref NotificationEcsTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:          
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-1-id"
            - !ImportValue
              Fn::Sub: "${Environment}-private-subnet-2-id"
          SecurityGroups:
            - !ImportValue
              Fn::Sub: "${Environment}-notification-sg-id"


Outputs:
  ClusterName:
    Description: Name of the ECS cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${Environment}-cluster-name"

  UserEcsServiceName:
    Description: Name of the User ECS service
    Value: !Ref UserEcsService
    Export:
      Name: !Sub "${Environment}-user-service"

  ProductEcsServiceName:
    Description: Name of the Product ECS service
    Value: !Ref ProductEcsService   
    Export:
      Name: !Sub "${Environment}-product-service"

  OrderEcsServiceName:
    Description: Name of the Order ECS service 
    Value: !Ref OrderEcsService
    Export:
      Name: !Sub "${Environment}-order-service"

  NotificationEcsServiceName:
    Description: Name of the Notification ECS service
    Value: !Ref NotificationEcsService 
    Export:
      Name: !Sub "${Environment}-notification-service"
