AWSTemplateFormatVersion: "2010-09-09"

Description: IAM Instance Profile stack for microservices project - ECS task execution role

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - staging
      - dev
      - prod
    Description: Environment name used to tag and name all resources

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-ecs-task-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: 
                - ecs-tasks.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Environment
          Value: !Ref Environment

  
  NotificationTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-notification-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: 
                - ecs-tasks.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "${Environment}-notification-task-sqs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !ImportValue
                  Fn::Sub: "${Environment}-OrdersQueueArn"
      Tags:
          - Key: Environment
            Value: !Ref Environment

  OrderTaskRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-order-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: 
                - ecs-tasks.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "${Environment}-order-task-service-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                Resource: !ImportValue
                  Fn::Sub: "${Environment}-OrdersQueueArn"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !ImportValue 
                    Fn::Sub: "${Environment}-orderdb-master-password-arn"
                
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ProductServiceTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-product-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: 
                - ecs-tasks.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "${Environment}-product-task-sqs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !ImportValue 
                    Fn::Sub: "${Environment}-productdb-master-password-arn"

      Tags:
        - Key: Environment
          Value: !Ref Environment 

 
  UserServiceTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-user-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: 
                - ecs-tasks.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "${Environment}-user-task-service-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !ImportValue
                    Fn::Sub: "${Environment}-userdb-master-password-arn"

      Tags:
        - Key: Environment
          Value: !Ref Environment

  ECSExecutionSecrets:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref ECSTaskExecutionRole
      PolicyName: !Sub "${Environment}-ecs-task-execution-secrets-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: 
              - !ImportValue 
                Fn::Sub: "${Environment}-userdb-master-password-arn"
              - !ImportValue 
                Fn::Sub: "${Environment}-orderdb-master-password-arn"
              - !ImportValue 
                Fn::Sub: "${Environment}-productdb-master-password-arn"



Outputs:
  ECSTaskExceutionRole:
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub "${Environment}-ecs-task-execution-role"
  
  NotificationTaskRole:
    Value: !GetAtt NotificationTaskRole.Arn
    Export:
      Name: !Sub "${Environment}-notification-task-role"
  UserTaskRole:
    Value: !GetAtt UserServiceTaskRole.Arn
    Export:
      Name: !Sub "${Environment}-user-task-role"

  ProductTaskRole:
    Value: !GetAtt ProductServiceTaskRole.Arn
    Export:
      Name: !Sub "${Environment}-product-task-role"

  OrderTaskRole:
    Value: !GetAtt OrderTaskRole.Arn
    Export:
      Name: !Sub "${Environment}-order-task-role"

