AWSTemplateFormatVersion: "2010-09-09"

Description: Observability stack for microservices project - CloudWatch Logs

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name used to tag and name all resources

  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues:
      - 7
      - 14
      - 30
      - 60
      - 90
    Description: Number of days to retain logs (shorter = cheaper)

Resources:
  # Log group for each service - where container logs are stored
  UserServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${Environment}-user-service"
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ProductServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${Environment}-product-service"
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment

  OrderServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${Environment}-order-service"
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment

  NotificationServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${Environment}-notification-service"
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment


Outputs:
  UserServiceLogGroupName:
    Description: Log group name for user service
    Value: !Ref UserServiceLogGroup
    Export:
      Name: !Sub "${Environment}-user-service-log-group-name"
  ProductServiceLogGroupName:
    Description: Log group name for product service
    Value: !Ref ProductServiceLogGroup
    Export:
      Name: !Sub "${Environment}-product-service-log-group-name"

  OrderServiceLogGroupName:
    Description: Log group name for order service
    Value: !Ref OrderServiceLogGroup
    Export:
      Name: !Sub "${Environment}-order-service-log-group-name"

  NotificationServiceLogGroupName:
    Description: Log group name for notification service
    Value: !Ref NotificationServiceLogGroup
    Export:
      Name: !Sub "${Environment}-notification-service-log-group-name"