AWSTemplateFormatVersion: "2010-09-09"

Description: RDS instance stack for microservices project. 

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - staging
      - dev
      - prod
    Description: Environment name used to tag and name all resources

  allocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage for RDS instance in GB

  dbInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: DB instance class for RDS instance

  dbengine:
    Type: String
    Default: postgres
    Description: Database engine for RDS instance (e.g. postgres, mysql)

  dbengineVersion:
    Type: String
    Default: "16.13"
    Description: Database engine version for RDS instance

  storageType:
    Type: String
    Default: gp2
    Description: Storage type for RDS instance (e.g. gp2, io1)

  dbName1:
    Type: String
    Default: userdb
    Description: Name of the database to create in RDS instance

  dbName2:
    Type: String
    Default: orderdb
    Description: Name of the database to create in RDS instance

  dbName3:
    Type: String
    Default: productdb
    Description: Name of the database to create in RDS instance

  dbMasterUsername:
    Type: String
    Default: dbadmin
    Description: Master username for RDS instance
  
Resources:

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${Environment}-rds-subnet-group"
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - Fn::ImportValue: !Sub "${Environment}-private-subnet-1-id"
        - Fn::ImportValue: !Sub "${Environment}-private-subnet-2-id"
  
  UserRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${Environment}-userdb-instance"
      AllocatedStorage: !Ref allocatedStorage
      DBInstanceClass: !Ref dbInstanceClass
      DBName: !Ref dbName1
      Engine: !Ref dbengine
      EngineVersion: !Ref dbengineVersion
      StorageType: !Ref storageType
      MasterUsername: !Ref dbMasterUsername
      MasterUserPassword: !ImportValue 
        Fn::Sub: "${Environment}-userdb-master-password
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${Environment}-rds-sg-id"
      DBSubnetGroupName: !Ref SubnetGroup
      MultiAZ: true
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-rds-instance"



  ProductRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${Environment}-productdb-instance"
      AllocatedStorage: !Ref allocatedStorage
      DBInstanceClass: !Ref dbInstanceClass
      DBName: !Ref dbName3
      Engine: !Ref dbengine
      EngineVersion: !Ref dbengineVersion
      StorageType: !Ref storageType
      MasterUsername: !Ref dbMasterUsername
      MasterUserPassword: !ImportValue 
        Fn::Sub: "${Environment}-productdb-master-password
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${Environment}-rds-sg-id"
      DBSubnetGroupName: !Ref SubnetGroup
      MultiAZ: true
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-rds-instance-2"


  OrderRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${Environment}-orderdb-instance"
      AllocatedStorage: !Ref allocatedStorage
      DBInstanceClass: !Ref dbInstanceClass
      DBName: !Ref dbName2
      Engine: !Ref dbengine
      EngineVersion: !Ref dbengineVersion
      StorageType: !Ref storageType
      MasterUsername: !Ref dbMasterUsername
      MasterUserPassword: !ImportValue 
        Fn::Sub: "${Environment}-orderdb-master-password
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${Environment}-rds-sg-id"
      DBSubnetGroupName: !Ref SubnetGroup
      MultiAZ: true
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-rds-instance-3"


Outputs:
  UserRDSInstanceEndpoint:
    Description: Endpoint for user RDS instance
    Value: !GetAtt UserRDSInstance.Endpoint.Address
    Export:
      Name: !Sub "${dbName1}-endpoint"

  ProductRDSInstanceEndpoint:
    Description: Endpoint for product RDS instance
    Value: !GetAtt ProductRDSInstance.Endpoint.Address
    Export:
      Name: !Sub "${dbName3}-endpoint"

  OrderRDSInstanceEndpoint:
    Description: Endpoint for order RDS instance
    Value: !GetAtt OrderRDSInstance.Endpoint.Address
    Export:
      Name: !Sub "${dbName2}-endpoint"

  UserDBIdentifier:
    Description: DB instance identifier for user RDS instance
    Value: !Ref UserRDSInstance
    Export:
      Name: !Sub "${dbName1}-identifier"

  ProductDBIdentifier:
    Description: DB instance identifier for product RDS instance
    Value: !Ref ProductRDSInstance
    Export: 
      Name: !Sub "${dbName3}-identifier"

  OrderDBIdentifier: 
    Description: DB instance identifier for order RDS instance
    Value: !Ref OrderRDSInstance
    Export:
      Name: !Sub "${dbName2}-identifier"