AWSTemplateFormatVersion: "2010-09-09"

Description: Secrets stack for microservices project

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - staging
      - dev
      - prod
    Description: Environment name used to tag and name all resources


Resources:
  UserDBMasterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-user-db-master-password"
      Description: Master password for user RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true

  OrderDBMasterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-order-db-master-password"
      Description: Master password for order RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true  

  ProductDBMasterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-product-db-master-password" 
      Description: Master password for product RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true


Outputs:
  UserDBMasterPasswordArn:
    Value: !GetAtt UserDBMasterPassword.Id
    Export:
      Name: !Sub "${Environment}-user-db-master-password-arn"

  OrderDBMasterPasswordArn:
    Value: !GetAtt OrderDBMasterPassword.Id
    Export:
      Name: !Sub "${Environment}-order-db-master-password-arn"

  ProductDBMasterPasswordArn:
    Value: !GetAtt ProductDBMasterPassword.Id
    Export:
      Name: !Sub "${Environment}-product-db-master-password-arn"