AWSTemplateFormatVersion: "2010-09-09"

Description: Secrets stack for microservices project

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - staging
      - dev
      - prod
    Description: Environment name used to tag and name all resources


Resources:
  UserDBMasterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-userdb-master-password"
      Description: Master password for user RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 12
        ExcludePunctuation: true

  OrderDBMasterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-orderdb-master-password"
      Description: Master password for order RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 12
        ExcludePunctuation: true  

  ProductDBMasterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-productdb-master-password" 
      Description: Master password for product RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 12
        ExcludePunctuation: true


Outputs:
  UserDBMasterPassword:
    Value: !Ref UserDBMasterPassword
    Export:
      Name: !Sub "${Environment}-userdb-master-password"

  OrderDBMasterPassword:
    Value: !Ref OrderDBMasterPassword
    Export:
      Name: !Sub "${Environment}-orderdb-master-password"

  ProductDBMasterPassword:
    Value: !Ref ProductDBMasterPassword
    Export:
      Name: !Sub "${Environment}-productdb-master-password"

  UserDBMasterPasswordARN:
    Value: !GetAtt UserDBMasterPassword.Id
    Export:
      Name: !Sub "${Environment}-userdb-master-password-arn"

  OrderDBMasterPasswordARN:
    Value: !GetAtt OrderDBMasterPassword.Id
    Export:
      Name: !Sub "${Environment}-orderdb-master-password-arn"

  ProductDBMasterPasswordARN:
    Value: !GetAtt ProductDBMasterPassword.Id
    Export:
      Name: !Sub "${Environment}-productdb-master-password-arn"

  
