AWSTemplateFormatVersion: "2010-09-09"

Description: Security Group stack for microservices project - SG for load balancer, ECS tasks and RDS instance

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - staging
      - dev
      - prod
    Description: Environment name used to tag and name all resources

  loadBalancerPort:
    Type: Number
    Default: 80
    Description: Port for load balancer to listen on

  RDSPort:
    Type: Number
    Default: 5432
    Description: Port for RDS instance to listen on

  UserServicePort:
    Type: Number
    Default: 3001
    Description: Port for user service to listen on

  ProductServicePort:
    Type: Number
    Default: 3002
    Description: Port for product service to listen on

  OrderServicePort:
    Type: Number
    Default: 3003
    Description: Port for order service to listen on
 
 


Resources:
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for load balancer
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref loadBalancerPort
          ToPort: !Ref loadBalancerPort 
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-lb-sg"

  UserServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref UserServicePort
          ToPort: !Ref UserServicePort
          SourceSecurityGroupId: !Ref LoadBalancerSG
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ecs-sg"

  ProductServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ProductServicePort
          ToPort: !Ref ProductServicePort
          SourceSecurityGroupId: !Ref LoadBalancerSG
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ecs-sg"

  OrderServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref OrderServicePort
          ToPort: !Ref OrderServicePort
          SourceSecurityGroupId: !Ref LoadBalancerSG
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ecs-sg"

  NotificationServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks 
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-vpc-id"
      #No inbound rules needed for notification service as it only consumes from SQS and does not receive traffic from load balancer

  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS instance
      VpcId: !ImportValue
        Fn::Sub: "${Environment}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref RDSPort
          ToPort: !Ref RDSPort
          SourceSecurityGroupId: !Ref UserServiceSG
        - IpProtocol: tcp
          FromPort: !Ref RDSPort
          ToPort: !Ref RDSPort
          SourceSecurityGroupId: !Red ProductService
        - IpProtocol: tcp
          FromPort: !Ref RDSPort
          ToPort: !Ref RDSPort
          SourceSecurityGroupId: !Ref OrderServiceSG
       
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-rds-sg"


Outputs:
  LoadBalancerSGId:
    Description: Security group ID for load balancer
    Value: !Ref LoadBalancerSG
    Export:
      Name: !Sub "${Environment}-lb-sg-id"

  ECSTaskSGId:
    Description: Security group ID for ECS tasks
    Value: !Ref ECSTaskSG
    Export:
      Name: !Sub "${Environment}-ecs-sg-id"

  RDSSGId:
    Description: Security group ID for RDS instance
    Value: !Ref RDSSG
    Export:
      Name: !Sub "${Environment}-rds-sg-id"
