AWSTemplateFormatVersion: "2010-09-09"

Description: Messaging Queue stack for microservices project

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - staging
      - dev
      - prod
    Description: Environment name used to tag and name all resources

  timeout:
    Type: Number
    Default: 30
    Description: Visibility timeout for the SQS queue in seconds

  retention:
    Type: Number
    Default: 180
    Description: Message retention period for the SQS queue in seconds


Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-notification-queue"
      VisibilityTimeout: !Ref timeout
      MessageRetentionPeriod: !Ref retention
      Tags:
        - Key: Environment
          Value: !Ref Environment


  OrdersDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-orders-dead-letter-queue"
      MessageRetentionPeriod: 180 # 3 minutes in seconds


  OrdersQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-orders-queue"
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrdersDeadLetterQueue.Arn
        maxReceiveCount: 5


      
Outputs:

  NotificationQueueArn:
    Description: ARN of notification queue
    Value: !GetAtt SQSQueue.Arn
    Export:
      Name: !Sub "${Environment}-NotificationQueueArn"

  NotificationQueueURL:
    Description: URL of notification queue
    Value: !Ref SQSQueue
    Export:
      Name: !Sub "${Environment}-NotificationQueueURL"


  OrdersQueueName:
    Description: Name of the orders SQS queue
    Value: !Ref OrdersQueue
    Export:
      Name: !Sub "${Environment}-OrdersQueueURL"

  OrderQueueArn:
    Description: ARN of the orders SQS queue
    Value: !GetAtt OrdersQueue.Arn
    Export:
      Name: !Sub "${Environment}-OrdersQueueArn"

  OrdersDeadLetterQueueName:
    Description: Name of the orders dead letter SQS queue 
    Value: !Ref OrdersDeadLetterQueue
    Export:
      Name: !Sub "${Environment}-OrdersDeadLetterQueueName"