name: Deploy a three tier application to AWS ECS Fargate using GitHub Actions
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:  
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      # # Validate CloudFormation templates
      # - name: Validate CloudFormation templates
      #   run: |
      #     cd cf-scripts
      #     pip install cfn-lint==0.87.0
      #     cfn-lint *.yaml 

      # Create infrastructure using CloudFormation
      - name: Deploy the First set of CloudFormation stack
        run: |
          cd cf-scripts
          ./deploy.sh dev

      # Retrieve ECR repository URIs from CloudFormation outputs
      - name: Retrieve user service repository URIs
        run: |
          echo "USER_ECR_URI=$(aws cloudformation describe-stacks \
            --stack-name microservice-ecr \
            --query "Stacks[0].Outputs[?OutputKey=='UserRepositoryUri'].OutputValue" \
            --output text)" >> $GITHUB_ENV

      - name: Retrieve product service repository URIs
        run: |
          echo "PRODUCT_ECR_URI=$(aws cloudformation describe-stacks \
            --stack-name microservice-ecr \
            --query "Stacks[0].Outputs[?OutputKey=='ProductRepositoryUri'].OutputValue" \
            --output text)" >> $GITHUB_ENV

      - name: Retrieve order service repository URIs
        run: |
          echo "ORDER_ECR_URI=$(aws cloudformation describe-stacks \
            --stack-name microservice-ecr \
            --query "Stacks[0].Outputs[?OutputKey=='OrderRepositoryUri'].OutputValue" \
            --output text)" >> $GITHUB_ENV

      - name: Retrieve notification service repository URIs
        run: |  
          echo "NOTIFICATION_ECR_URI=$(aws cloudformation describe-stacks \
            --stack-name microservice-ecr \
            --query "Stacks[0].Outputs[?OutputKey=='NotificationRepositoryUri'].OutputValue" \
            --output text)" >> $GITHUB_ENV


      # Login to AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com


      # Build and push Docker images for User service
      - name: Build and push user service
        run: |
          docker build -t user-service ./app/user-service
          docker tag user-service:latest $USER_ECR_URI:latest
          docker push $USER_ECR_URI:latest

      # Build and push Docker images for Product service
      - name: Build and push product service
        run: |
          docker build -t product-service ./app/product-service
          docker tag product-service:latest $PRODUCT_ECR_URI:latest
          docker push $PRODUCT_ECR_URI:latest

      # Build and push Docker images for Order service
      - name: Build and push order service
        run: |
          docker build -t order-service ./app/order-service
          docker tag order-service:latest $ORDER_ECR_URI:latest
          docker push $ORDER_ECR_URI:latest
      

      # Build and push Docker images for Notification service
      - name: Build and push notification service
        run: |
          docker build -t notification-service ./app/notification-service
          docker tag notification-service:latest $NOTIFICATION_ECR_URI:latest
          docker push $NOTIFICATION_ECR_URI:latest


      # Docker images needs to be pushed to ECR before creating the ECS services,
      # otherwise the CloudFormation stack creation will fail due to missing images. 
      # Therefore, we are deploying the infrastructure in two steps. In the first step, we create some of  the infrastructre, 
      #and in the second step, we create the ECS services after pushing the Docker images to ECR.


      # Continue creating  infrastructure using CloudFormation
      - name: Deploy the Second set of CloudFormation stack
        run: |
          cd cf-scripts
          ./deploy2.sh dev